INSERT INTO authors (id, Author) VALUES
(1, 'J.K. Rowling'),
(2, 'Suzanne Collins'),
(3, 'Stephenie Meyer'),
(4, 'Frank Herbert'),
(5, 'Veronica Roth'),
(6, 'Dan Brown'),
(7, 'George R.R. Martin'),
(8, 'Stephen King'),
(9, 'C.S. Lewis'),
(10, 'Andy Weir'),
(11, 'Harper Lee'),
(12, 'Charles Duhigg'),
(13, 'Robert C. Martin'),
(14, 'Edwin A. Abbott'),
(15, 'Yuval Noah Harari'),
(16, 'Rick Riordan'),
(17, 'Gillian Flynn'),
(18, 'Mark Manson'),
(19, 'George Orwell'),
(20, 'J.D. Salinger'),
(21, 'J.R.R. Tolkien'),
(22, 'Holly Black'),
(23, 'Sarah J. Maas'),
(24, 'Pierce Brown'),
(25, 'Brent Weeks'),
(26, 'Lauren Roberts'),
(27, 'Tim Ferriss'),
(28, 'Robin Sharma'),
(29, 'James Clear'),
(30, 'Hal Elrod'),
(31, 'Marijn Haverbeke'),
(32, 'Kyle Simpson'),
(33, 'Douglas Crockford'),
(34, 'Michael Hartl'),
(35, 'Taherah Mafi'),
(36, 'Alexandra Bracken'),
(37, 'Jennifer Lynn Barnes'),
(38, 'Dale Carnegie'),
(39, 'Stephen R. Covey'),
(40, 'Paula Hawkins');